version: '3.3'
services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kelp
        ports:
            - "127.0.0.1:3316:3306"
        volumes:
            - database:/var/lib/mysql

    app:
        image: nginx:alpine
        volumes:
            - .:/app
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - php
        ports:
            - "127.0.0.1:8003:80"

    php:
        build: ./docker/php
        user: php
        working_dir: /app
        links:
            - db
        volumes:
            - .:/app

volumes:
  database: ~
