kelp.product.list:
    path: /storage/{id}/list/product/{page}
    controller: App\Controller\ProductController::listAction
    defaults:
        page: 1
    requirements:
        page: '\d+'

kelp.product.create:
    path: /storage/{id}/create/product
    controller: App\Controller\ProductController::createAction
    requirements:
        page: '\d+'

kelp.product.edit:
    path: /product/edit/{id}
    controller: App\Controller\ProductController::editAction
    requirements:
        id: '\d+'

kelp.product.delete:
    path: /product/delete/{id}
    controller: App\Controller\ProductController::deleteAction
    requirements:
            id: '\d+'
